services:
  - type: web
    name: hsil-korean-msg-api
    env: go
    region: singapore
    plan: free
    buildCommand: go build -tags netgo -ldflags '-s -w' -o main
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        value: postgresql://anymodb_user:lQ11owYzyp03O7tRibPL2gonpJYiZ3pB@dpg-cvsd7j95pdvs73bjq0gg-a.singapore-postgres.render.com/anymodb
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    autoDeploy: true 