services:
  - type: web
    name: hsil-korean-msg-api
    env: go
    region: singapore
    plan: free
    buildCommand: go build -tags netgo -ldflags '-s -w' -o main
    startCommand: ./main
    envVars:
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
    autoDeploy: true 